/**
 * Go2kavkaz Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@icerockdev.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {GuideStatus} from './guideStatus';

export interface GuideListData {
  id: number;
  /**
   * Guide Name
   */
  name: string;
  avatar: string;
  cityName: string;
  /**
   * Cost per 1 hour
   */
  costPerHour: number;
  age: number;
  /**
   * About of guide
   */
  description: string;
  /**
   * Guide phone
   */
  isHide: boolean;
  phone?: string;
  email: string;
  status: GuideStatus;
}
