/**
 * Go2kavkaz Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@icerockdev.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type MessageStatus = 'SEND' | 'READ' | 'NOT_SENT';

export const MessageStatus = {
  SEND: 'SEND' as MessageStatus,
  READ: 'READ' as MessageStatus,
  NOT_SENT: 'NOT_SENT' as MessageStatus,
};
