/**
 * Go2kavkaz Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@icerockdev.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type TravelMode =
  | 'FOOT'
  | 'CAR'
  | 'BIKE'
  | 'BUS'
  | 'MOTORCYCLE'
  | 'BOAT'
  | 'MUSEUM'
  | 'HORSEBACK'
  | 'IN_DOOR';

export const TravelMode = {
  FOOT: 'FOOT' as TravelMode,
  CAR: 'CAR' as TravelMode,
  BIKE: 'BIKE' as TravelMode,
  BUS: 'BUS' as TravelMode,
  MOTORCYCLE: 'MOTORCYCLE' as TravelMode,
  BOAT: 'BOAT' as TravelMode,
  MUSEUM: 'MUSEUM' as TravelMode,
  HORSEBACK: 'HORSEBACK' as TravelMode,
  IN_DOOR: 'IN_DOOR' as TravelMode,
};
