/**
 * Go2kavkaz Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@icerockdev.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type BookingStatus =
  | 'WAITING_PARTNER'
  | 'WAITING_PAYMENT'
  | 'PARTNER_ACCEPTED'
  | 'PAID'
  | 'CANCELLED';

export const BookingStatus = {
  WAITING_PARTNER: 'WAITING_PARTNER' as BookingStatus,
  WAITING_PAYMENT: 'WAITING_PAYMENT' as BookingStatus,
  PARTNER_ACCEPTED: 'PARTNER_ACCEPTED' as BookingStatus,
  PAID: 'PAID' as BookingStatus,
  CANCELLED: 'CANCELLED' as BookingStatus,
};
