/**
 * Go2kavkaz Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@icerockdev.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface BookingGuideRequestBody {
  firstName?: string;
  lastName?: string;
  phone?: string;
  email?: string;
  bookingComments?: string;
  /**
   * Number of adult people
   */
  adultCount: number;
  /**
   * Number of children
   */
  childrenCount?: number;
  date?: string;
  time?: string;
  /**
   * Duration of work
   */
  duration: number | null;
  guideId: number;
  /**
   * UUID
   */
  idempotenceKey: string;
}
