/**
 * Go2kavkaz Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@icerockdev.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {BookingRoomStaysData} from './bookingRoomStaysData';
import {ShortPartnerData} from './shortPartnerData';
import {Location} from '../common/location';

export interface BookingPlacementData {
  id: number;
  partnerData: ShortPartnerData;
  name: string;
  email: string;
  phone: string;
  images: Array<string>;
  city: string;
  address?: string;
  coordinate?: Location;
  stayUnitKind?: string;
  rating?: number;
  roomStays?: BookingRoomStaysData[];
}
