/**
 * Go2kavkaz Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@icerockdev.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {ExcursionType} from '@/modules/excursion/types';
import {TravelMode} from '@/modules/core/api/model/common/travelMode';
import {ExcursionGuideData} from '@/modules/core/api/model/booking/excursionGuideData';
import {Location} from '@/modules/core/api/model/common/location';

export interface BookingExcursionData {
  id: number;
  name: string;
  description: string;
  type: ExcursionType;
  travelMode: TravelMode;
  coordinate: Location;
  mainImage: string;
  images: Array<string>;
  /**
   * Number of participants
   */
  numberOfParticipants?: number;
  /**
   * Number of children
   */
  numberOfChildren?: number;
  duration: number;
  excursionDate: string;
  excursionTime: string;
  guide: ExcursionGuideData;
  meetingPlaceDescription?: string;
}
