/**
 * Go2kavkaz Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@icerockdev.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {PlacementFilterData} from './placementFilterData';
import {PlacementServiceData} from './placementServiceData';
import {PlacementRateData} from './placementRateData';
import {Room} from './room';
import {ShortPartnerData} from '../booking/shortPartnerData';
import {Location} from '../common/location';

export interface DetailedPlacementData {
  id: number;
  placementExternalId?: string;
  partner: ShortPartnerData;
  name: string;
  /**
   * Guide email
   */
  email: string;
  /**
   * Guide phone
   */
  phone: string;
  /**
   * Minio main key
   */
  images: Array<string>;
  city: string;
  cityId: number;
  address?: string;
  coordinate?: Location;
  stayUnitKind?: string;
  rating?: number;
  stars?: number;
  ratePlans?: Array<PlacementRateData>;
  rooms: Array<Room>;
  services?: Array<PlacementServiceData>;
  isHide: boolean;
  specialOffer: boolean;
  comment?: string;
  filterDto?: PlacementFilterData;
}
