/**
 * Go2kavkaz Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@icerockdev.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {PlacementExtraData} from './placementExtraData';
import {PlacementType} from './placementType';
import {PlacementRateData} from './placementRateData';
import {Location} from '../common/location';

export interface PlacementData {
  id: number;
  name: string;
  description?: string;
  city: string;
  cityId?: number | null;
  address?: string;
  avatar: string;
  coordinate: Location;
  rating?: number;
  stars?: number;
  ratePlans: Array<PlacementRateData>;
  isHide: boolean;
  comment?: string;
  extraData?: PlacementExtraData;
  placementType?: PlacementType;
}
