/**
 * Go2kavkaz Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@icerockdev.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type PlacementType = 'HOTEL' | 'APARTMENTS' | 'GUEST_HOUSE' | 'OTHER';

export const PlacementType = {
  HOTEL: 'HOTEL' as PlacementType,
  APARTMENTS: 'APARTMENTS' as PlacementType,
  GUEST_HOUSE: 'GUEST_HOUSE' as PlacementType,
  OTHER: 'OTHER' as PlacementType,
};
