/**
 * Go2kavkaz Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@icerockdev.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {RoomTypeData} from './roomTypeData';
import {BookingExtraServiceData} from '../booking/bookingExtraServiceData';
import {GuestData} from '../booking/guestData';
import {RatePlanData} from '../booking/ratePlanData';
import {QuestsCountData} from '../booking/questsCountData';
import {StayDatesData} from '../booking/stayDatesData';

export interface RoomStaysData {
  stayDates?: StayDatesData;
  ratePlan?: RatePlanData;
  roomType?: RoomTypeData;
  guests?: Array<GuestData>;
  guestCount?: QuestsCountData;
  services?: Array<BookingExtraServiceData>;
  checksum?: string;
}
