/**
 * Go2kavkaz Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@icerockdev.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {NotificationType} from './notificationType';

export interface NotificationData {
  id: number;
  message: string;
  isRead: boolean;
  meta?: {[key: string]: string} | null;
  type?: NotificationType;
}
