/**
 * Go2kavkaz Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@icerockdev.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ExcursionBaseData {
  /**
   * Excursion name
   */
  name: string;
  /**
   * Excursion description
   */
  description: string;
  /**
   * Price for adult people
   */
  adultPrice: number;
  /**
   * Price for children
   */
  childrenPrice?: number;
  /**
   * Excursion duration
   */
  duration: number;
  /**
   * Max participants count
   */
  maxNumberOfParticipants: number;
  /**
   * Is it possible with children or not
   */
  withChildren?: boolean;
}
