/**
 * Go2kavkaz Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@icerockdev.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {ExcursionStatus} from './excursionStatus';
import {ExcursionGuidePublicData} from './excursionGuidePublicData';

export interface ExcursionListDataAllOf {
  id?: number;
  cityName?: string;
  mainPhotoUrl?: string;
  status?: ExcursionStatus;
  guide?: ExcursionGuidePublicData;
}
