/**
 * Go2kavkaz Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@icerockdev.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {ScheduleDate} from '../common/scheduleDate';
import {ExcursionGuidePublicData} from './excursionGuidePublicData';
import {ExcursionType} from './excursionType';
import {TravelMode} from '../common/travelMode';
import {ExcursionGuideData} from '@/modules/core/api/model/booking/excursionGuideData';

export interface BookingExcursionData {
  name: string;
  description: string;
  type: ExcursionType;
  travelMode: TravelMode;
  coordinate: Location;
  mainImage: string;
  images: Array<string>;
  /**
   * Number of participants
   */
  numberOfParticipants?: number;
  /**
   * Number of children
   */
  numberOfChildren?: number;
  duration: number;
  excursionDate: string;
  excursionTime: string;
  guide?: ExcursionGuideData;
}

export interface ExcursionData {
  id: number;
  name: string;
  guide: ExcursionGuidePublicData;
  commission: number;
  cityName: string;
  description: string;
  adultPrice: number;
  childrenPrice?: number;
  duration: number;
  meetingPlaceDescription: string;
  maxNumberOfParticipants: number;
  withChildren?: boolean;
  schedule: Array<ScheduleDate & object>;
  type: ExcursionType;
  travelMode: TravelMode;
  images: string[];
  coordinate: {
    lat: number;
    lng: number;
  };
  countOfParticipants: number;
  childrenCount: number;
  excursionDate: string;
  excursionTime: string;
  mainPhoto: string;
  photos: Array<string>;
}
