/**
 * Go2kavkaz Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@icerockdev.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {Location} from '../common/location';

export interface ExcursionFilledDataAllOf {
  /**
   * City ID
   */
  cityId?: number;
  /**
   * Excursion duration
   */
  duration?: number;
  /**
   * Number of hours before the start of the excursion to close registration
   */
  registrationClosingHoursCount?: number;
  /**
   * Description of meeting place
   */
  meetingPlaceDescription?: string;
  meetingPlace?: Location;
  /**
   * Minio key
   */
  mainPhoto?: string;
  photos?: Array<string>;
}
