/**
 * Go2kavkaz Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@icerockdev.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {ExcursionType} from './excursionType';
import {ScheduleDate} from '../common/scheduleDate';
import {TravelMode} from '../common/travelMode';
import {Location} from '../common/location';

export interface UpdateExcursionRequestBody {
  /**
   * City ID
   */
  cityId: number;
  /**
   * Excursion duration
   */
  duration: number;
  /**
   * Number of hours before the start of the excursion to close registration
   */
  registrationClosingHoursCount?: number;
  /**
   * Description of meeting place
   */
  meetingPlaceDescription: string;
  meetingPlace: Location;
  /**
   * Minio key
   */
  mainPhoto: string;
  photos: Array<string>;
  /**
   * Guide Name
   */
  guideName: string;
  /**
   * Guide phone
   */
  guidePhone: string;
  /**
   * Guide email
   */
  guideEmail: string;
  /**
   * Guide avatar image key
   */
  guideAvatar: string;
  /**
   * Excursion name
   */
  name: string;
  /**
   * Excursion description
   */
  description: string;
  /**
   * Price for adult people
   */
  adultPrice: number;
  /**
   * Price for children
   */
  childrenPrice: number;
  /**
   * Max participants count
   */
  maxNumberOfParticipants: number;
  /**
   * Is it possible with children or not
   */
  withChildren?: boolean;
  schedule: Array<ScheduleDate>;
  type: ExcursionType;
  travelMode: TravelMode;
  isHide?: boolean;
}
