export const childAgeOptions: {value: string; title: string}[] = [
  {value: '0', title: '0 лет'},
  {value: '1', title: '1 год'},
  {value: '2', title: '2 года'},
  {value: '3', title: '3 года'},
  {value: '4', title: '4 года'},
  {value: '5', title: '5 лет'},
  {value: '6', title: '6 лет'},
  {value: '7', title: '7 лет'},
  {value: '8', title: '8 лет'},
  {value: '9', title: '9 лет'},
  {value: '10', title: '10 лет'},
  {value: '11', title: '11 лет'},
  {value: '12', title: '12 лет'},
  {value: '13', title: '13 лет'},
  {value: '14', title: '14 лет'},
  {value: '15', title: '15 лет'},
  {value: '16', title: '16 лет'},
  {value: '17', title: '17 лет'},
];
