/**
 * Go2kavkaz Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@icerockdev.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {Role} from './role';

export interface UserProfileData {
  id: number;
  firstName: string;
  lastName: string;
  middleName?: string;
  /**
   * Guide email
   */
  email: string;
  /**
   * Guide phone
   */
  phone?: string;
  /**
   * User avatar url
   */
  avatar?: string;
  birthdayDate?: string;
  company?: string;
  commission?: string;
  requisites?: string;
  role: Role;
  personalPaymentId?: string;
}
