/**
 * Go2kavkaz Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@icerockdev.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type UserStatus =
  | 'ACTIVE'
  | 'BLOCKED'
  | 'AUTO_REGISTERED'
  | 'CHECKING_EMAIL'
  | 'CHECKING_CONTRACT';

export const UserStatus = {
  ACTIVE: 'ACTIVE' as UserStatus,
  BLOCKED: 'BLOCKED' as UserStatus,
  AUTO_REGISTERED: 'AUTO_REGISTERED' as UserStatus, // Only for tourist
  CHECKING_EMAIL: 'CHECKING_EMAIL' as UserStatus,
  CHECKING_CONTRACT: 'CHECKING_CONTRACT' as UserStatus, // Only for partner
};
